# Generated by Django 4.0 on 2021-12-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobseekerProfile',
            new_name='WorkerProfile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_jobseeker',
            new_name='is_worker',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
