# Generated by Django 4.0 on 2022-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microhr', '0003_application_application_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pass_or_fail',
            field=models.BooleanField(default=0, null=True, verbose_name='合否'),
        ),
    ]
