# Generated by Django 4.0 on 2022-03-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microhr', '0005_remove_application_pass_or_fail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='microhr.work', verbose_name='求人'),
        ),
    ]
